# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url:
    weight: 10
  - name: Projects
    url: projects
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Publications
    url: publication
    weight: 50
  - name: Teaching
    url: teaching
    weight: 60
  - name: Lab Wiki
    url: lab-wiki
    weight: 70
  - name: Contact
    url: contact
    weight: 80